# Generated by Django 4.2.1 on 2023-05-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyinfodjango',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storyinfodjango',
            name='chapterCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storyinfodjango',
            name='chapters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storyinfodjango',
            name='wholeStory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
