# Generated by Django 4.2.1 on 2023-05-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="length", field=models.DurationField(max_length=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_character",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
