# Generated by Django 4.2.1 on 2023-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_alter_item_length_alter_item_main_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="length", field=models.TimeField(max_length=10),
        ),
    ]
