# Generated by Django 4.2.1 on 2023-05-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.TimeField(auto_now=True),
        ),
    ]
